//******************************************************************
//
// Copyright 2014 Samsung Electronics All Rights Reserved.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OC_Cm_Server_ResourceHandler_IResourceHandler */

#ifndef _Included_OC_Cm_Server_ResourceHandler_IResourceHandler
#define _Included_OC_Cm_Server_ResourceHandler_IResourceHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OC_Cm_Server_ResourceHandler_IResourceHandler
 * Method:    getNativeGlobleReference
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_OC_Cm_Server_ResourceHandler_IResourceHandler_getNativeGlobleReference
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
