//******************************************************************
//
// Copyright 2014 Samsung Electronics All Rights Reserved.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OC_Cm_Connector_Server_ServerSession */

#ifndef _Included_OC_Cm_Connector_Server_ServerSession
#define _Included_OC_Cm_Connector_Server_ServerSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OC_Cm_Connector_Server_ServerSession
 * Method:    constructNativeSession
 * Signature: (IJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_OC_Cm_Connector_Server_ServerSession_constructNativeSession
(JNIEnv *, jobject, jint, jlong, jstring, jstring);

/*
 * Class:     OC_Cm_Connector_Server_ServerSession
 * Method:    getClientAddress
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_OC_Cm_Connector_Server_ServerSession_getClientAddress
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_Connector_Server_ServerSession
 * Method:    getClientDevice
 * Signature: (J)LSec/Cm/Device;
 */
JNIEXPORT jobject JNICALL Java_OC_Cm_Connector_Server_ServerSession_getClientDevice
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_Connector_Server_ServerSession
 * Method:    getServerId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_OC_Cm_Connector_Server_ServerSession_getServerId
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_Connector_Server_ServerSession
 * Method:    setResponseHeader
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Connector_Server_ServerSession_setResponseHeader
(JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     OC_Cm_Connector_Server_ServerSession
 * Method:    getTemplateParameter
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_OC_Cm_Connector_Server_ServerSession_getTemplateParameter
(JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
