//******************************************************************
//
// Copyright 2014 Samsung Electronics All Rights Reserved.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OC_Cm_DeviceFinder_IDeviceFinder */

#ifndef _Included_OC_Cm_DeviceFinder_IDeviceFinder
#define _Included_OC_Cm_DeviceFinder_IDeviceFinder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OC_Cm_DeviceFinder_IDeviceFinder
 * Method:    addDevice
 * Signature: (JILjava/lang/String;Ljava/lang/String;LOC/Cm/Client/Resource/IResourceResponseListener;)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_DeviceFinder_IDeviceFinder_addDevice
(JNIEnv *, jobject, jlong, jint, jstring, jstring, jobject);

/*
 * Class:     OC_Cm_DeviceFinder_IDeviceFinder
 * Method:    refresh
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_DeviceFinder_IDeviceFinder_refresh
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_DeviceFinder_IDeviceFinder
 * Method:    setDeviceFinderListener
 * Signature: (JLOC/Cm/DeviceFinder/IDeviceFinderListener;)J
 */
JNIEXPORT jlong JNICALL
Java_OC_Cm_DeviceFinder_IDeviceFinder_setDeviceFinderListener__JLOC_Cm_DeviceFinder_IDeviceFinderListener_2
(JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     OC_Cm_DeviceFinder_IDeviceFinder
 * Method:    setDeviceFinderListener
 * Signature: (JILOC/Cm/DeviceFinder/IDeviceFinderListener;)V
 */
JNIEXPORT void JNICALL
Java_OC_Cm_DeviceFinder_IDeviceFinder_setDeviceFinderListener__JILOC_Cm_DeviceFinder_IDeviceFinderListener_2
(JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     OC_Cm_DeviceFinder_IDeviceFinder
 * Method:    setDeviceFinderListener
 * Signature: (JIILOC/Cm/DeviceFinder/IDeviceFinderListener;)V
 */
JNIEXPORT void JNICALL
Java_OC_Cm_DeviceFinder_IDeviceFinder_setDeviceFinderListener__JIILOC_Cm_DeviceFinder_IDeviceFinderListener_2
(JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     OC_Cm_DeviceFinder_IDeviceFinder
 * Method:    getDevices
 * Signature: (J)[LOC/Cm/Device;
 */
JNIEXPORT jobjectArray JNICALL Java_OC_Cm_DeviceFinder_IDeviceFinder_getDevices__J
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_DeviceFinder_IDeviceFinder
 * Method:    getDevices
 * Signature: (JI)[LOC/Cm/Device;
 */
JNIEXPORT jobjectArray JNICALL Java_OC_Cm_DeviceFinder_IDeviceFinder_getDevices__JI
(JNIEnv *, jobject, jlong, jint);

/*
 * Class:     OC_Cm_DeviceFinder_IDeviceFinder
 * Method:    getDevices
 * Signature: (JII)[LOC/Cm/Device;
 */
JNIEXPORT jobjectArray JNICALL Java_OC_Cm_DeviceFinder_IDeviceFinder_getDevices__JII
(JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     OC_Cm_DeviceFinder_IDeviceFinder
 * Method:    removeDeviceFinderListener
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_OC_Cm_DeviceFinder_IDeviceFinder_removeDeviceFinderListener
(JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
