//******************************************************************
//
// Copyright 2014 Samsung Electronics All Rights Reserved.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OC_Cm_Serialization_ISerializable */

#ifndef _Included_OC_Cm_Serialization_ISerializable
#define _Included_OC_Cm_Serialization_ISerializable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OC_Cm_Serialization_ISerializable
 * Method:    constructNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_OC_Cm_Serialization_ISerializable_constructNative
(JNIEnv *, jobject);

/*
 * Class:     OC_Cm_Serialization_ISerializable
 * Method:    deleteNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_OC_Cm_Serialization_ISerializable_deleteNative
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_Serialization_ISerializable
 * Method:    serialize
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializable_serialize
(JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     OC_Cm_Serialization_ISerializable
 * Method:    deSerialize
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializable_deSerialize
(JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     OC_Cm_Serialization_ISerializable
 * Method:    validateContent
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializable_validateContent
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_Serialization_ISerializable
 * Method:    setInstanceName
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializable_setInstanceName
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     OC_Cm_Serialization_ISerializable
 * Method:    setList
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_OC_Cm_Serialization_ISerializable_setList
(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
