//******************************************************************
//
// Copyright 2014 Samsung Electronics All Rights Reserved.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OC_Cm_Serialization_ISerializer */

#ifndef _Included_OC_Cm_Serialization_ISerializer
#define _Included_OC_Cm_Serialization_ISerializer

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    setStringPropertyValue
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_setStringPropertyValue
(JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    setBoolPropertyValue
 * Signature: (JLjava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_setBoolPropertyValue
(JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    setIntPropertyValue
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_setIntPropertyValue
(JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    setDoublePropertyValue
 * Signature: (JLjava/lang/String;D)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_setDoublePropertyValue
(JNIEnv *, jobject, jlong, jstring, jdouble);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    startDocument
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_startDocument
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    endDocument
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_endDocument
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    startGroupProperty
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_startGroupProperty
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    endGroupProperty
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_endGroupProperty
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    getContentType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_OC_Cm_Serialization_ISerializer_getContentType
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    setSchemaInstanceType
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_setSchemaInstanceType
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    setLongPropertyValue
 * Signature: (JLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_setLongPropertyValue
(JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    isInFilteringMode
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_isInFilteringMode
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    isRecursive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_isRecursive
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    validateMandatory
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_validateMandatory
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    setErrorMessage
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_OC_Cm_Serialization_ISerializer_setErrorMessage
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    startListProperty
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_startListProperty
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    endListProperty
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_endListProperty
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    setIDExcemption
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_OC_Cm_Serialization_ISerializer_setIDExcemption
(JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     OC_Cm_Serialization_ISerializer
 * Method:    getIDExcemption
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_OC_Cm_Serialization_ISerializer_getIDExcemption
(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
