//******************************************************************
//
// Copyright 2014 Samsung Electronics All Rights Reserved.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OC_Cm_Notification_NotificationResponse */

#ifndef _Included_OC_Cm_Notification_NotificationResponse
#define _Included_OC_Cm_Notification_NotificationResponse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OC_Cm_Notification_NotificationResponse
 * Method:    constructNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_OC_Cm_Notification_NotificationResponse_constructNative
(JNIEnv *, jobject, jstring, jstring, jstring, jlong);

/*
 * Class:     OC_Cm_Notification_NotificationResponse
 * Method:    deleteNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_OC_Cm_Notification_NotificationResponse_deleteNative
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_Notification_NotificationResponse
 * Method:    setResourcePath
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_OC_Cm_Notification_NotificationResponse_setResourcePath
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     OC_Cm_Notification_NotificationResponse
 * Method:    setNotificationType
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_OC_Cm_Notification_NotificationResponse_setNotificationType
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     OC_Cm_Notification_NotificationResponse
 * Method:    setNotificationData
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_OC_Cm_Notification_NotificationResponse_setNotificationData
(JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     OC_Cm_Notification_NotificationResponse
 * Method:    setUUID
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_OC_Cm_Notification_NotificationResponse_setUUID
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     OC_Cm_Notification_NotificationResponse
 * Method:    getUUID
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_OC_Cm_Notification_NotificationResponse_getUUID
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_Notification_NotificationResponse
 * Method:    getResourcePath
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_OC_Cm_Notification_NotificationResponse_getResourcePath
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_Notification_NotificationResponse
 * Method:    getNotificationType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_OC_Cm_Notification_NotificationResponse_getNotificationType
(JNIEnv *, jobject, jlong);

/*
 * Class:     OC_Cm_Notification_NotificationResponse
 * Method:    getNotificationData
 * Signature: (J)LOC/Cm/Serialization/ISerializable;
 */
JNIEXPORT jobject JNICALL Java_OC_Cm_Notification_NotificationResponse_getNotificationData
(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
