//******************************************************************
//
// Copyright 2014 Samsung Electronics All Rights Reserved.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class _Connector_HeadersList */

#ifndef _Included__Connector_HeadersList
#define _Included__Connector_HeadersList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     _Connector_HeadersList
 * Method:    setHeader
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java__Connector_HeadersList_setHeader
(JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     _Connector_HeadersList
 * Method:    getHeader
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java__Connector_HeadersList_getHeader
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     _Connector_HeadersList
 * Method:    getHeaderNameList
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java__Connector_HeadersList_getHeaderNameList
(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
