##
# NotificationManager build script
##

Import('env')

if env.get('RELEASE'):
	env.AppendUnique(CCFLAGS = ['-Os'])
	env.AppendUnique(CPPDEFINES = ['NDEBUG'])
else:
	env.AppendUnique(CCFLAGS = ['-g'])
	env.AppendUnique(CPPDEFINES = ['-DTB_LOG'])

lib_env = env.Clone()
SConscript(env.get('SRC_DIR') + '/service/third_party_libs.scons', 'lib_env')
notimgr_env = lib_env.Clone()

target_os = env.get('TARGET_OS')
######################################################################
# Build flags
######################################################################
notimgr_env.AppendUnique(CPPPATH = ['NotificationManager/include'])
notimgr_env.AppendUnique(CPPPATH = ['../../extlibs/cjson'])
notimgr_env.AppendUnique(CPPPATH = ['../../resource/csdk/logger/include'])
notimgr_env.PrependUnique(LIBS = ['oc', 'octbstack', 'oc_logger', 'coap'])

if target_os not in ['windows', 'winrt']:
	notimgr_env.AppendUnique(CXXFLAGS = ['-O2', '-g', '-Wall', '-fmessage-length=0'])

if target_os == 'linux':
	notimgr_env.AppendUnique(LIBS = ['pthread'])

if target_os == 'android':
	notimgr_env.AppendUnique(CXXFLAGS = ['-frtti', '-fexceptions'])
	notimgr_env.AppendUnique(LIBS = ['gnustl_static'])

	if not env.get('RELEASE'):
		notimgr_env.AppendUnique(LIBS = ['log'])

######################################################################
# Source files and Targets
######################################################################
NOTI_SRC_DIR = 'NotificationManager/src/'
notimgr_src = [
        NOTI_SRC_DIR + 'hosting.c',
        NOTI_SRC_DIR + 'requestHandler.c',
        NOTI_SRC_DIR + 'virtualResource.c']

notificationsdk = notimgr_env.StaticLibrary('NOTISDKLibrary', notimgr_src)

notimgr_env.InstallTarget(notificationsdk, 'libNMSDK')

# Go to build sample apps
SConscript('SampleApp/SConscript')
