##
# NotificationManager build script
##

Import('env')

lib_env = env.Clone()
SConscript(env.get('SRC_DIR') + '/service/third_party_libs.scons', 'lib_env')
notimgr_env = lib_env.Clone()

target_os = env.get('TARGET_OS')
######################################################################
# Build flags
######################################################################
notimgr_env.AppendUnique(CPPPATH = ['NotificationManager/include'])
notimgr_env.AppendUnique(CPPPATH = ['../../extlibs/cjson'])
notimgr_env.AppendUnique(CPPPATH = ['../../resource/csdk/logger/include'])
notimgr_env.PrependUnique(LIBS = ['oc', 'octbstack', 'oc_logger', 'coap'])

if target_os not in ['windows', 'winrt']:
	notimgr_env.AppendUnique(CXXFLAGS = ['-O2', '-g', '-Wall', '-fmessage-length=0'])

if target_os == 'linux':
	notimgr_env.AppendUnique(LIBS = ['pthread'])

if target_os == 'android':
	notimgr_env.AppendUnique(CXXFLAGS = ['-frtti', '-fexceptions'])
	notimgr_env.AppendUnique(LIBS = ['gnustl_static'])
        notimgr_env.AppendUnique(LIBS = ['log'])
	if not env.get('RELEASE'):
		notimgr_env.AppendUnique(LIBS = ['log'])

######################################################################
# Source files and Targets
######################################################################
NOTI_SRC_DIR = 'NotificationManager/src/'
notimgr_src = [
		NOTI_SRC_DIR + 'hosting.c',
		NOTI_SRC_DIR + 'requestHandler.c',
		NOTI_SRC_DIR + 'virtualResource.c',
		NOTI_SRC_DIR + 'resourceCoordinator_JNI.cpp']

static_libResourceHosting = notimgr_env.StaticLibrary(
		target = 'NotificationManager',
		source = [notimgr_src]
		)

notimgr_env.AppendUnique(LIBPATH = [env.get('BUILD_DIR')])

shared_libResourceHosting = notimgr_env.SharedLibrary(
		target = 'NotificationManager',
		source = [notimgr_src]
		)

notimgr_env.InstallTarget([shared_libResourceHosting, static_libResourceHosting], 'libResouceHosting')

# Go to build sample apps
SConscript('SampleApp/SConscript')
