#******************************************************************
#
# Copyright (c) 2018 LG Electronics, Inc.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


#######################################################
#       Build IP adapter for webOS
#######################################################
import os

Import('connectivity_env')

connectivity_env.ParseConfig("pkg-config --cflags --libs glib-2.0")
connectivity_env.ParseConfig("pkg-config --cflags --libs luna-service2")
connectivity_env.ParseConfig("pkg-config --cflags --libs pbnjson_c")

connectivity_env.AppendUnique(CA_SRC=[File('caipnwmonitor.c')])

connectivity_env.AppendUnique(CPPDEFINES=['__webos__'])
