##
# This script includes windows specific config (MSVS/MSVC)
##
Import('env', 'RELEASE_BUILD', 'TARGET_CPU_ARCH')

# Set common flags
env.AppendUnique(CXXFLAGS=['/wd4244', '/wd4267','/wd4345', '/wd4355', '/wd4800', '/wd4996'])
env.AppendUnique(CFLAGS=['/EHsc'])
env.AppendUnique(CXXFLAGS=['/EHsc'])

# Set release/debug flags
if RELEASE_BUILD:
	env.AppendUnique(CFLAGS = ['/MD', '/O2', '/GF'])
	env.AppendUnique(CXXFLAGS = ['/MD', '/O2', '/GF'])
	env.AppendUnique(CPPDEFINES = ['NDEBUG'])
else:
	env.AppendUnique(CFLAGS = ['/MDd', '/Od', '/ZI', '/GZ', '/Gm'])
	env.AppendUnique(CXXFLAGS = ['/MDd', '/Od', '/ZI', '/GZ', '/Gm'])
	env.AppendUnique(CPPDEFINES = ['_DEBUG'])
	env.AppendUnique(LINKFLAGS = ['/debug'])