#######################################################
#       Build IP adapter for Ardunino
#######################################################
import os

Import('connectivity_env')

connectivity_env.PrependUnique(CPPPATH=Dir('.'))

src_files = None
if connectivity_env.get('SHIELD') == 'WIFI':
    src_files = [
        File('caipclient_wifi.cpp'),
        File('caipserver_wifi.cpp'),
        File('caipnwmonitor_wifi.cpp')
    ]
else:
    src_files = [
        File('caipadapterutils_eth.cpp'),
        File('caipclient_eth.cpp'),
        File('caipserver_eth.cpp'),
        File('caipnwmonitor_eth.cpp')
    ]

connectivity_env.AppendUnique(CA_SRC=src_files)
