#%RAML 0.8
#RAML for Light Resource
title: Resource Light
version: 1.0
mediaType : application/json
schemas:
- 
  lightPublish: !include oic.light.json

/oic/light:
  displayName: Resource Light
  description: |
    Resource to be exposed by any OIC Device that can act as Light
  get:
    description: |
      Get the attributes of light
    responses:
      200:
        description: |
          Respond with the selector criteria
        body:
          application/json:
            schema: !include oic.light.json
            example: |
              {
              
              }