/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "NSProviderInterface.h"
#include "NSCommon.h"
/* Header for class com_sec_notiproviderjni_IoTNotification */

#ifndef NOTIFICATION_JNI_H
#define NOTIFICATION_JNI_H
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_sec_notiproviderjni_IoTNotification
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
 JNIEXPORT jint JNICALL Java_org_iotivity_service_notification_IoTNotification_NSStartProvider
 (JNIEnv *, jobject, jboolean);

 JNIEXPORT jint JNICALL Java_org_iotivity_service_notification_IoTNotification_NSStopProvider
  (JNIEnv *, jobject);

 JNIEXPORT jint JNICALL Java_org_iotivity_service_notification_IoTNotification_NSSendNotification
  (JNIEnv *, jobject, jobject);

 JNIEXPORT jint JNICALL Java_org_iotivity_service_notification_IoTNotification_NSProviderReadCheck
  (JNIEnv *, jobject, jobject);

 JNIEXPORT jint JNICALL Java_org_iotivity_service_notification_IoTNotification_NSAccept
  (JNIEnv *, jobject, jobject, jboolean);

 void JNIlogPrintedCallback(JNIEnv*, jobject, const char*);

 void JNISubscribeRequestCallback(JNIEnv*, jobject, char*);

 void JNIMessageSyncCallback(JNIEnv*, jobject, char*);

 void NSSubscribeRequestCb(NSConsumer*);

 void NSSyncCb(NSProvider*, NSSync*);


#ifdef __cplusplus
}
#endif
#endif
