#######################################################
#       Build TCP adapter for Ardunino
#######################################################
import os

Import('connectivity_env')

connectivity_env.PrependUnique(CPPPATH=Dir('.'))

src_files = None
if connectivity_env.get('SHIELD') == 'ETH':
    src_files = [
        File('catcpserver_eth.cpp'),
        File('catcpadapterutils_eth.cpp')
    ]
else:
    msg = "\nError: TCP is not supported for WIFI shield"
    Exit(msg)

connectivity_env.AppendUnique(CA_SRC=src_files)
