##
# Build script for DTLS Relay
#
##

tinydtls_path='../../../../extlibs/tinydtls/'
def __install(ienv, targets, name):
	i_n = ienv.Install(env.get(tinydtls_path), targets)
	Alias(name, i_n)
	env.AppendUnique(TS = [name])

env = Environment()
env.AddMethod(__install, 'InstallTarget')
env.AddMethod(__install, 'UserInstallTargetLib')
env.AppendUnique(RELEASE=True)
env.SConscript(tinydtls_path + 'SConscript', exports='env')
src_dir='src'
build_dir='bin/linux/'
env.VariantDir(build_dir, src_dir, duplicate=0)
env.SConscript(build_dir+'SConscript', exports='env')
