#******************************************************************
#
# Copyright 2014 Samsung Electronics All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
##
#sample-app build script
##
Import('env')

# Add third party libraries
lib_env = env.Clone()
SConscript(env.get('SRC_DIR') + '/service/third_party_libs.scons', 'lib_env')

sample_env = lib_env.Clone()
target_os = env.get('TARGET_OS')
######################################################################
# Build flags
######################################################################
sample_env.AppendUnique(CPPPATH = [
				'../../plugin-manager/src/',
				'../../lib/cpluff/libcpluff/',
				env.get('SRC_DIR') + '/extlibs/rapidxml/'])

if target_os not in ['windows', 'winrt']:
	sample_env.AppendUnique(CXXFLAGS = ['-Wall', '-pthread', '-std=c++0x'])

sample_env.AppendUnique(LIBS = ['oc', 'oc_logger', 'octbstack',
                                'connectivity_abstraction', 'coap',
                                'ppm', 'pmimpl', 'dl'])

if env.get('SECURED') == '1':
    sample_env.AppendUnique(LIBS = ['tinydtls'])

# On some platforms link order can miss functions so librt needs to be
# re-scanned at the end if present. gcc 4.6 is one with this issue.
if 'rt' in sample_env.get('LIBS'):
    sample_env.Append(LIBS = ['rt'])

sample_env.AppendUnique(LIBS = ['pthread'])
######################################################################
# Source files and Targets
######################################################################
mqttclient = sample_env.Program('mqtt/mqttclient', 'mqtt/mqttclient.cpp')

Command("mqtt/pluginmanager.xml","../../plugin-manager/src/pluginmanager.xml", Copy("$TARGET", "$SOURCE"))
Command("mqtt/libpmimpl.so","../../../../libpmimpl.so", Copy("$TARGET", "$SOURCE"))

Alias('mqttclient', mqttclient)
env.AppendTarget('mqttclient')
