#******************************************************************
#
# Copyright 2014 Samsung Mobile Communications GmbH All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


env = Environment()
env.Replace(CC = "g++")
iotdir = '/home/kimheesung/IOT/iotivity/'
######################################################################
# Build flags
######################################################################
env.AppendUnique(CPPPATH = [
        iotdir + '/resource/include',
        iotdir + 'resource/oc_logger/include',
        iotdir + 'resource/csdk/stack/include',
		iotdir + 'resource/c_common/',
        'intf/inc',
        'bin/inc',
        ])



env.AppendUnique(LIBPATH = [iotdir + 'out/linux/x86_64/release/'])
env.AppendUnique(CXXFLAGS = ['-std=c++11', '-fpermissive', '-Wall',  '-fPIC', '-g'])
env.PrependUnique(LIBS = ['oc', 'octbstack', 'oc_logger'])

######################################################################
# Source files and Targets
######################################################################
wsisrc = [
        'wsiclient.cpp'
]
wsi = env.Program('wsi', wsisrc)
