/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iotivity_jar_CALeInterface */

#ifndef _Included_com_iotivity_jar_CALeInterface
#define _Included_com_iotivity_jar_CALeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iotivity_jar_CALeInterface
 * Method:    CARegisterLeScanCallback
 * Signature: (Landroid/bluetooth/BluetoothAdapter/LeScanCallback;)V
 */
JNIEXPORT void JNICALL Java_com_iotivity_jar_CALeInterface_CARegisterLeScanCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_iotivity_jar_CALeInterface
 * Method:    CARegisterLeGattCallback
 * Signature: (Landroid/bluetooth/BluetoothGattCallback;)V
 */
JNIEXPORT void JNICALL Java_com_iotivity_jar_CALeInterface_CARegisterLeGattCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_iotivity_jar_CALeInterface
 * Method:    CALeScanCallback
 * Signature: (Landroid/bluetooth/BluetoothDevice;I[B)V
 */
JNIEXPORT void JNICALL Java_com_iotivity_jar_CALeInterface_CALeScanCallback
  (JNIEnv *, jobject, jobject, jint, jbyteArray);

/*
 * Class:     com_iotivity_jar_CALeInterface
 * Method:    CALeGattConnectionStateChangeCallback
 * Signature: (Landroid/bluetooth/BluetoothGatt;II)V
 */
JNIEXPORT void JNICALL Java_com_iotivity_jar_CALeInterface_CALeGattConnectionStateChangeCallback
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_iotivity_jar_CALeInterface
 * Method:    CALeGattServicesDiscoveredCallback
 * Signature: (Landroid/bluetooth/BluetoothGatt;I)V
 */
JNIEXPORT void JNICALL Java_com_iotivity_jar_CALeInterface_CALeGattServicesDiscoveredCallback
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_iotivity_jar_CALeInterface
 * Method:    CALeGattCharacteristicReadCallback
 * Signature: (Landroid/bluetooth/BluetoothGatt;Landroid/bluetooth/BluetoothGattCharacteristic;I)V
 */
JNIEXPORT void JNICALL Java_com_iotivity_jar_CALeInterface_CALeGattCharacteristicReadCallback
  (JNIEnv *, jobject, jobject, jobject, jstring, jint);

/*
 * Class:     com_iotivity_jar_CALeInterface
 * Method:    CALeGattCharacteristicWritjclasseCallback
 * Signature: (Landroid/bluetooth/BluetoothGatt;Landroid/bluetooth/BluetoothGattCharacteristic;I)V
 */
JNIEXPORT void JNICALL Java_com_iotivity_jar_CALeInterface_CALeGattCharacteristicWriteCallback
  (JNIEnv *, jobject, jobject, jobject, jstring, jint);

/*
 * Class:     com_iotivity_jar_CALeInterface
 * Method:    CALeGattCharacteristicChangedCallback
 * Signature: (Landroid/bluetooth/BluetoothGatt;Landroid/bluetooth/BluetoothGattCharacteristic;)V
 */
JNIEXPORT void JNICALL Java_com_iotivity_jar_CALeInterface_CALeGattCharacteristicChangedCallback
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     com_iotivity_jar_CALeInterface
 * Method:    CALeGattDescriptorReadCallback
 * Signature: (Landroid/bluetooth/BluetoothGatt;Landroid/bluetooth/BluetoothGattDescriptor;I)V
 */
JNIEXPORT void JNICALL Java_com_iotivity_jar_CALeInterface_CALeGattDescriptorReadCallback
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     com_iotivity_jar_CALeInterface
 * Method:    CALeGattDescriptorWriteCallback
 * Signature: (Landroid/bluetooth/BluetoothGatt;Landroid/bluetooth/BluetoothGattDescriptor;I)V
 */
JNIEXPORT void JNICALL Java_com_iotivity_jar_CALeInterface_CALeGattDescriptorWriteCallback
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     com_iotivity_jar_CALeInterface
 * Method:    CALeGattReliableWriteCompletedCallback
 * Signature: (Landroid/bluetooth/BluetoothGatt;I)V
 */
JNIEXPORT void JNICALL Java_com_iotivity_jar_CALeInterface_CALeGattReliableWriteCompletedCallback
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_iotivity_jar_CALeInterface
 * Method:    CALeGattReadRemoteRssiCallback
 * Signature: (Landroid/bluetooth/BluetoothGatt;II)V
 */
JNIEXPORT void JNICALL Java_com_iotivity_jar_CALeInterface_CALeGattReadRemoteRssiCallback
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
