/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iotivity_jar_CAWiFiInterface */

#ifndef _Included_com_iotivity_jar_CAWiFiInterface
#define _Included_com_iotivity_jar_CAWiFiInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iotivity_jar_CAWiFiInterface
 * Method:    CAWiFiStateEnabled
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iotivity_jar_CAWiFiInterface_CAWiFiStateEnabled
(JNIEnv *, jclass);

/*
 * Class:     com_iotivity_jar_CAWiFiInterface
 * Method:    CAWiFiStateDisabled
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iotivity_jar_CAWiFiInterface_CAWiFiStateDisabled
(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
