#######################################################
#       Build BLE adapter for Tizen
#######################################################

Import('env', 'src_dir')
import os.path

env.PrependUnique(CPPPATH = [ os.path.join(src_dir, 'tizen'),
                              './con/lib/tizen/ble/inc',
                              './con/lib/tizen/ble/inc/mobile' ])

env.ParseConfig("pkg-config --cflags --libs capi-network-bluetooth")

src_files = [ 'cableclient.c',
              'cableserver.c',
              'cableutil.c',
              'cablenwmonitor.c']

Return('src_files')
