##
# protocol plugin build script
##
import platform

Import('env')

SConscript('lib/cpluff/SConscript')
SConscript('plugin-manager/SConscript')

# The code include pthread_cancel method, can't build on android
# MQTT requires openssl, forbid cross compile as it isn't ready
if env.get('TARGET_OS') != 'android':
	SConscript('plugins/SConscript')

SConscript('sample-app/SConscript')
