##
# CA build script
##

Import('env')

connectivity_env = env.Clone()
target_os = connectivity_env.get('TARGET_OS')
transport = connectivity_env.get('TARGET_TRANSPORT')
build_sample = connectivity_env.get('BUILD_SAMPLE')
with_ra = connectivity_env.get('WITH_RA')
with_tcp = connectivity_env.get('WITH_TCP')
with_mq = connectivity_env.get('WITH_MQ')

print("Given Transport is %s" % transport)
print("Given OS is %s" % target_os)
print("BUILD_SAMPLE is %s" % build_sample)
print("MQ flag is %s" % with_mq)

SConscript('src/SConscript', exports='connectivity_env')
