##
# The main build script
#
##

# Load common build config
# Load common build config
SConscript('./build/SConscript')

Import('env')

sample_env = env.Clone()

target_os = env.get('TARGET_OS')
transport = env.get('TARGET_TRANSPORT')
secured = env.get('SECURED')
release_mode = env.get('RELEASE')
buildsample = env.get('BUILD_SAMPLE')

print "Given Transport is %s" % transport
print "Given OS is %s" % target_os
print "Secured %s" % env.get('SECURED')
print "Build sample is set to %s" % buildsample

build_dir = env.get('BUILD_DIR')

if target_os == 'tizen':
	command = "sh build/tizen/gbsbuild.sh %s %s %s" % (transport, buildsample, release_mode)
	print "Created Command is %s" % command
	gbs_script = env.Command('gbs_build', None, command)
	AlwaysBuild ('gbs_script')
elif target_os == 'arduino':
	SConscript('build/arduino/arduino.scons')

        # Build 'libcoap' library
        SConscript(build_dir + 'lib/libcoap-4.1.1/SConscript')

        # Build 'src' sub-project
        SConscript(build_dir + 'SConscript')

        # Build 'samples' sub-project
        SConscript(build_dir + 'samples/arduino/SConscript')
elif target_os == 'linux':

	# Build 'libcoap' library
	SConscript(build_dir  + 'lib/libcoap-4.1.1/SConscript')

	# Build 'src' sub-project
	SConscript(build_dir + 'SConscript')

	# Build 'samples' sub-project
	env.SConscript(build_dir + 'samples/linux/SConscript')
elif target_os == 'android':

	# Build 'libcoap' library
	SConscript(build_dir  + 'lib/libcoap-4.1.1/SConscript')

	# Build 'src' sub-project
	SConscript(build_dir + 'SConscript')

	# Build 'samples' sub-project
	env.SConscript(build_dir + 'samples/android/SConscript')
