##
# CA build script
##

Import('env')

target_os = env.get('TARGET_OS')
transport = env.get('TARGET_TRANSPORT')

print "Given Transport is %s" % transport
print "Given OS is %s" % target_os

targets_disallow_multitransport = ['arduino']

if target_os in targets_disallow_multitransport:
    if ('ALL' in transport) or (len(transport) != 1):
        print "*** Error invalid option values: TARGET_TRANSPORT"
        print "%s disallowed until testing can validate use of multiple transports on %s %d" % (transport, target_os, len(transport))
        Exit(1)

if 'ALL' in transport:
	if target_os == 'linux':
		env.AppendUnique(CPPDEFINES = ['WIFI_ADAPTER', 'ETHERNET_ADAPTER','NO_EDR_ADAPTER','NO_LE_ADAPTER'])
	elif target_os == 'tizen':
		env.AppendUnique(CPPDEFINES = ['WIFI_ADAPTER', 'NO_ETHERNET_ADAPTER','EDR_ADAPTER','LE_ADAPTER'])
	else:
		env.AppendUnique(CPPDEFINES = ['WIFI_ADAPTER', 'ETHERNET_ADAPTER','EDR_ADAPTER','LE_ADAPTER'])
	print "CA Transport is ALL"
else:
	if 'BT' in transport:
		if target_os == 'linux':
			print "CA Transport BT is not supported in Linux"
			Exit(1)
		else:
			env.AppendUnique(CPPDEFINES = ['EDR_ADAPTER'])
			print "CA Transport is BT"
	else:
		env.AppendUnique(CPPDEFINES = ['NO_EDR_ADAPTER'])

	if 'BLE' in transport:
		if target_os == 'linux':
			print "CA Transport BLE is not supported in Linux"
			Exit(1)
		else:
			env.AppendUnique(CPPDEFINES = ['LE_ADAPTER'])
			print "CA Transport is BLE"
	else:
		env.AppendUnique(CPPDEFINES = ['NO_LE_ADAPTER'])

	if 'WIFI' in transport:
		env.AppendUnique(CPPDEFINES = ['WIFI_ADAPTER'])
		print "CA Transport is WIFI"
	else:
		env.AppendUnique(CPPDEFINES = ['NO_WIFI_ADAPTER'])
	if 'ETHERNET' in transport:
		env.AppendUnique(CPPDEFINES = ['ETHERNET_ADAPTER'])
		print "CA Transport is ETHERNET"
	else:
		env.AppendUnique(CPPDEFINES = ['NO_ETHERNET_ADAPTER'])

env.SConscript('./src/SConscript')

