#******************************************************************
#
# Copyright 2017 Samsung Electronics All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

######################################################################
# Smart Home API Common build script
######################################################################
Import('env');
smarthome_env = env.Clone()
target_os = smarthome_env.get('TARGET_OS')

smarthome_env.AppendUnique(CPPPATH = [
        '../../../resource/csdk/include/',
        '../../../resource/csdk/stack/include',
        '../../../resource/c_common/ocrandom/include',
        '../../../resource/csdk/logger/include',
        '../../../resource/csdk/security/include',
        ])

smarthome_env.AppendUnique(LIBPATH = [smarthome_env.get('BUILD_DIR')])
smarthome_env.AppendUnique(RPATH = [smarthome_env.get('BUILD_DIR')])
smarthome_env.PrependUnique(LIBS = ['coap'])
smarthome_env.AppendUnique(LIBS = ['connectivity_abstraction'])
smarthome_env.AppendUnique(LIBS = ['oc_logger'])
smarthome_env.AppendUnique(LIBS = ['octbstack'])

if 'g++' in smarthome_env.get('CXX'):
    smarthome_env.AppendUnique(CXXFLAGS = ['-Wall'])
    smarthome_env.AppendUnique(CXXFLAGS = ['-fPIC'])

######################################################################
# smarthome_common_api build script
######################################################################

smarthome_env.AppendUnique(CPPPATH= [
        '../common/include',
        '../common/internal'
        ])

######################################################################
# Source files and Targets
######################################################################

smarthome_common_src = ['src/PropertyBundle.cpp',
                        'src/PayloadConverter.cpp',
                        'src/SHPlatform.cpp',
                        'src/SHPlatform_Impl.cpp']

smarthomelib = smarthome_env.SharedLibrary('smarthome_common_api', smarthome_common_src)
smarthome_env.InstallTarget(smarthomelib, 'smarthome_common_api')
