##
# Examples build script
##
Import('env')

target_os = env.get('TARGET_OS')
if target_os in ['linux', 'windows', 'winrt', 'msys_nt']:
    SConscript('linux/SConscript')
elif target_os == 'android':
    SConscript('android/SConscript')
