//******************************************************************
//
// Copyright 2014 Samsung Electronics All Rights Reserved.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=



#ifndef ElEMENTS_H_
#define ElEMENTS_H_

#include "list"
#include "string"

#include "Device.h"
#include "List.h"
#include "Networks.h"
#include "Resource.h"
#include "Configuration.h"
#include "Events.h"
#include "Energy.h"
#include "Alarms.h"
#include "Record.h"
#include "Level.h"
#include "Devices.h"
#include "DRLC.h"
#include "Operation.h"
#include "AccessPoints.h"
#include "UsageLimit.h"
#include "Records.h"
#include "Version.h"
#include "Light.h"
#include "Versions.h"
#include "DevicesLink.h"
#include "Movement.h"
#include "EnergyLink.h"
#include "Humidity.h"
#include "Subscription.h"
#include "Network.h"
#include "Door.h"
#include "Subscriptions.h"
#include "LongPollingNotification.h"
#include "Thermostat.h"
#include "Usage.h"
#include "AccessPoint.h"
#include "ConfigurationLink.h"
#include "Detection.h"
#include "MessagesLink.h"
#include "Time.h"
#include "EnergyConsumption.h"
#include "Message.h"
#include "Alarm.h"
#include "Temperatures.h"
#include "Temperature.h"
#include "Link.h"
#include "Information.h"
#include "SubscriptionsLink.h"
#include "Usages.h"
#include "LongPollingNotificationLink.h"
#include "UsageLimits.h"
#include "RecordsLink.h"
#include "IdentifiedObject.h"
#include "InformationLink.h"
#include "Specification.h"
#include "Doors.h"
#include "NotificationsLink.h"
#include "WiFi.h"
#include "Color.h"
#include "Mode.h"
#include "Notification.h"
#include "AccessPointsLink.h"
#include "Capability.h"
#include "Actuators.h"
#include "Messages.h"
#include "Image.h"
#include "PatternsLink.h"
#include "ActionsLink.h"
#include "FoodManagerLink.h"

#define EN_DEVICE "Device"
#define EN_FOODLISTLINK "FoodListLink"
#define EN_FOODIMAGE "FoodImage"
#define EN_GROUPS "Groups"
#define EN_LIST "List"
#define EN_AVSOURCESLINK "AVSourcesLink"
#define EN_NETWORKS "Networks"
#define EN_OVEN "Oven"
#define EN_FOODLIST "FoodList"
#define EN_RESOURCE "Resource"
#define EN_SHOPPING "Shopping"
#define EN_MEDIAINFOS "MediaInfos"
#define EN_CONFIGURATION "Configuration"
#define EN_EVENTS "Events"
#define EN_ENERGY "Energy"
#define EN_ALARMS "Alarms"
#define EN_RECORD "Record"
#define EN_DEFROSTRESERVATION "DefrostReservation"
#define EN_PATTERNS "Patterns"
#define EN_AVSOURCES "AVSources"
#define EN_CHANNELINFOS "ChannelInfos"
#define EN_LEVEL "Level"
#define EN_DEVICES "Devices"
#define EN_DRLC "DRLC"
#define EN_OPERATION "Operation"
#define EN_ACCESSPOINTS "AccessPoints"
#define EN_USAGELIMIT "UsageLimit"
#define EN_CAPTURE "Capture"
#define EN_RECORDS "Records"
#define EN_WIND "Wind"
#define EN_VERSION "Version"
#define EN_LIGHT "Light"
#define EN_VERSIONS "Versions"
#define EN_AV "AV"
#define EN_WASHER "Washer"
#define EN_CUSTOMRECIPESLINK "CustomRecipesLink"
#define EN_DEVICESLINK "DevicesLink"
#define EN_MOVEMENT "Movement"
#define EN_CAPTURES "Captures"
#define EN_ENERGYLINK "EnergyLink"
#define EN_HUMIDITY "Humidity"
#define EN_FRIDGE "Fridge"
#define EN_SUBSCRIPTION "Subscription"
#define EN_NETWORK "Network"
#define EN_DOOR "Door"
#define EN_SUBSCRIPTIONS "Subscriptions"
#define EN_SHOPPINGLISTLINK "ShoppingListLink"
#define EN_PATTERNSLINK "PatternsLink"
#define EN_LONGPOLLINGNOTIFICATION "LongPollingNotification"
#define EN_PATTERN "Pattern"
#define EN_THERMOSTAT "Thermostat"
#define EN_FOOD "Food"
#define EN_FOODMANAGER "FoodManager"
#define EN_USAGE "Usage"
#define EN_ACCESSPOINT "AccessPoint"
#define EN_CONFIGURATIONLINK "ConfigurationLink"
#define EN_IMAGE "Image"
#define EN_DETECTION "Detection"
#define EN_ACTION "Action"
#define EN_MESSAGESLINK "MessagesLink"
#define EN_TIME "Time"
#define EN_DEFROSTRESERVATIONS "DefrostReservations"
#define EN_GROUPSLINK "GroupsLink"
#define EN_ENERGYCONSUMPTION "EnergyConsumption"
#define EN_MESSAGE "Message"
#define EN_ALARM "Alarm"
#define EN_TEMPERATURES "Temperatures"
#define EN_TEMPERATURE "Temperature"
#define EN_SHOPPINGLIST "ShoppingList"
#define EN_LINK "Link"
#define EN_INFORMATION "Information"
#define EN_AUDIO "Audio"
#define EN_SUBSCRIPTIONSLINK "SubscriptionsLink"
#define EN_USAGES "Usages"
#define EN_LONGPOLLINGNOTIFICATIONLINK "LongPollingNotificationLink"
#define EN_CUSTOMRECIPES "CustomRecipes"
#define EN_ACTIONSLINK "ActionsLink"
#define EN_USAGELIMITS "UsageLimits"
#define EN_RECORDSLINK "RecordsLink"
#define EN_GROUP "Group"
#define EN_IDENTIFIEDOBJECT "IdentifiedObject"
#define EN_AVSOURCE "AVSource"
#define EN_INFORMATIONLINK "InformationLink"
#define EN_SPECIFICATION "Specification"
#define EN_FOODMANAGERLINK "FoodManagerLink"
#define EN_REMOTE "Remote"
#define EN_CUSTOMRECIPE "CustomRecipe"
#define EN_DOORS "Doors"
#define EN_ACTIONS "Actions"
#define EN_NOTIFICATIONSLINK "NotificationsLink"
#define EN_CAMERA "Camera"
#define EN_WIFI "WiFi"
#define EN_COLOR "Color"
#define EN_FOODIMAGESLINK "FoodImagesLink"
#define EN_MODE "Mode"
#define EN_NOTIFICATION "Notification"
#define EN_ACCESSPOINTSLINK "AccessPointsLink"
#define EN_FOODIMAGES "FoodImages"
#define EN_PATTERNELEMENTS "PatternElements"
#define EN_CAPABILITY "Capability"
#define EN_ACTUATORS "Actuators"
#define EN_MESSAGES "Messages"
#define EN_CAPTURESLINK "CapturesLink"

#endif
