##
# 'service' sub-project main build script
#
##
Import('env')
Import('targets_csdk_only')

target_os = env.get('TARGET_OS')

if target_os not in targets_csdk_only:
	# Build things manager project
	SConscript('things-manager/SConscript')

	# Build soft sensor manager project
	SConscript('soft-sensor-manager/SConscript')

	# Build protocol plugin project
	# protocol-plugin use 'inotify', this feature isn't support by MAC OSX
	if target_os not in ['darwin', 'ios']:
		SConscript('protocol-plugin/SConscript')

	# Build notification manager project
	SConscript('notification-manager/SConscript')
#else:
#	SConscript('notification-manager/SampleApp/arduino/SConscript')
