##
# 'service' sub-project main build script
#
##
Import('env')

target_os = env.get('TARGET_OS')

if target_os != 'arduino':
	# Build things manager project
	SConscript('things-manager/SConscript')

	# Build soft sensor manager project
	SConscript('soft-sensor-manager/SConscript')

	# Build protocol plugin project
	# protocol-plugin use 'sys/inotify.h', this header file doesn't
	# exist on MAC OSX
	if target_os not in ['darwin', 'ios']:
		SConscript('protocol-plugin/SConscript')

	# Build notification manager project
	SConscript('notification-manager/SConscript')
else:
	SConscript('notification-manager/SampleApp/arduino/SConscript')
