##
# 'service' sub-project main build script
#
##
Import('env')

target_os = env.get('TARGET_OS')

if target_os != 'arduino':
	# Build things manager project
	SConscript('things-manager/SConscript')

	# Build soft sensor manager project
	SConscript('soft-sensor-manager/SConscript')

	# Build protocol plugin project
	SConscript('protocol-plugin/SConscript')

	# Build notification manager project
#	SConscript('notification-manager/SConscript')

	# Build control manager project
#	SConscript('control-manager/SConstruct')
else:
#	SConscript('notification-manager/SampleApp/arduino/SConscript')
