# build producer notification wrapper
SConscript('provider/SConscript')

# build producer notification wrapper
SConscript('consumer/SConscript')

# Go to build sample apps using wrapper
SConscript('examples/linux/SConscript')
