##
# NotificationManager build script
##

Import('env')

notimgr_env = env.Clone()

######################################################################
# Build flags
######################################################################
resource_path = env.get('SRC_DIR') + '/resource'

notimgr_env.AppendUnique(CPPPATH = [
		resource_path + '/oc_logger/include',
		resource_path + '/csdk/stack/include',
		resource_path + '/csdk/ocsocket/include',
		resource_path + '/csdk/logger/include'
		])

notimgr_env.AppendUnique(LIBPATH = [env.get('BUILD_DIR')])
notimgr_env.PrependUnique(LIBS = ['octbstack', 'coap'])

######################################################################
# Source files and Targets
######################################################################
thserver = notimgr_env.Program('thserver', 'thserver.cpp')
notimgr_env.CreateBin('thserver')

i_thserver = notimgr_env.Install(env.get('BUILD_DIR'), thserver)

Alias('thserver_arduino', i_thserver)
env.AppendTarget('thserver_arduino')