##
# Plugin Interface build script
##

Import('env')

target_os = env.get('TARGET_OS')

if target_os not in ['android', 'arduino', 'darwin', 'ios']:
    transport = env.get('TARGET_TRANSPORT')
    build_sample = env.get('BUILD_SAMPLE')

    env.SConscript('./src/SConscript')

    env.SConscript('./unittests/SConscript')

    if build_sample == 'ON':
	    if target_os in ['linux']:
		    target_path = target_os
		    env.SConscript('./samples/' + target_path + '/SConscript')

