#######################################################
#       Build IP adapter for Tizen
#######################################################
import os

Import('connectivity_env')

connectivity_env.ParseConfig("pkg-config --cflags --libs capi-network-connection")

connectivity_env.AppendUnique(CA_SRC=[File('caipnwmonitor.c')])
