#######################################################
#	Build Common Util
#######################################################

Import('env')
import os.path

print "Reading util folder script"

ca_os = env.get('TARGET_OS')
ca_transport = env.get('TARGET_TRANSPORT')
target_os = env.get('TARGET_OS')
project_root = env.get('SRC_DIR')
with_cloud = env.get('WITH_CLOUD')
with_tcp = env.get('WITH_TCP')
root_dir = os.path.join(project_root, 'resource', 'csdk', 'connectivity')
src_dir = os.path.join(root_dir, 'util', 'src')

######################################################################
# Source files to build common for platforms
######################################################################

env.AppendUnique(CA_SRC = [os.path.join('./../util/src/cautilinterface.c')])

if target_os == 'android':
	if (('BLE' in ca_transport) or ('ALL' in ca_transport)):
			env.AppendUnique(CA_SRC = [
			os.path.join(src_dir, 'camanager', 'bt_le_manager', 'android', 'caleconnectionmanager.c'),
			os.path.join(src_dir, 'camanager', 'bt_le_manager', 'android', 'caleautoconnector.c'),
			os.path.join(src_dir, 'camanager', 'bt_le_manager', 'android', 'camanagerleutil.c'),
			os.path.join(src_dir, 'camanager', 'bt_le_manager', 'android', 'camanagerdevice.c')])

	if (('BT' in ca_transport) or ('ALL' in ca_transport)):
			env.AppendUnique(CA_SRC = [
			os.path.join(src_dir, 'btpairing' ,'android', 'cabtpairing.c')])

if (with_cloud == True) and (with_tcp == True):
    env.AppendUnique(CPPDEFINES = ['WITH_CLOUD'])
    env.AppendUnique(CA_SRC = [
		os.path.join(src_dir, 'camanager', 'caconnectionmanager.c'),
		os.path.join(src_dir, 'camanager', 'camanagerutil.c'),
		os.path.join(src_dir, 'camanager', 'camessagearbiter.c'),
		os.path.join(src_dir, 'camanager', 'capolicymanager.c')])

