# *****************************************************************
#
#  Copyright 2015 Samsung Electronics All Rights Reserved.
#
#
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# *****************************************************************/

Import('env')

timer_env = env.Clone()

target_os = timer_env.get('TARGET_OS')

# Required for arduino builds to have access to Timer.h.
if target_os == 'arduino':
    timer_env.Replace(CC = env.get('CXX'))
    timer_env.Replace(CFLAGS = env.get('CXXFLAGS'))
elif target_os == 'windows':
    timer_env.AppendUnique(CCFLAGS = ['/W4', '/WX'])

libtimer = timer_env.StaticLibrary('timer', ['timer.c'], OBJPREFIX='libtimer_')
timer_env.InstallTarget(libtimer, 'timer');
