##
# linux sample app  build script
##

Import('env')

# Add third party libraries
SConscript(env.get('SRC_DIR') + '/service/third_party_libs.scons')
linux_sample_env = env.Clone()

######################################################################
# Build flags
######################################################################
linux_sample_env.AppendUnique(CPPPATH = ['include/'])
linux_sample_env.AppendUnique(CXXFLAGS = ['-std=c++0x', '-Wall', '-pthread'])
linux_sample_env.AppendUnique(CPPDEFINES = ['LINUX'])
linux_sample_env.AppendUnique(LIBPATH = [env.get('BUILD_DIR')])
linux_sample_env.AppendUnique(LIBS = ['pthread'])

######################################################################
#build sampleapp
######################################################################
thsensorapp1 = linux_sample_env.Program('THSensorApp', 'src/ThingResourceServer1.cpp')
Alias("thsensorapp1_sample", thsensorapp1)
env.AppendTarget('thsensorapp1_sample')
