##
# 'resource' sub-project main build script
#
##

import os

Import('env')

target_os = env.get('TARGET_OS')
src_dir = env.get('SRC_DIR')

# Build libcoap
SConscript('csdk/connectivity/lib/libcoap-4.1.1/SConscript')

# Build connectivity
SConscript('csdk/connectivity/SConscript')

# Build libocsrm
SConscript('csdk/security/SConscript')

# Build liboctbstack
SConscript('csdk/SConscript')

if target_os != 'arduino':
	# Build liboc_logger
	SConscript('oc_logger/SConscript')

	# Build liboc
	SConscript('src/SConscript')

	# Build examples
	SConscript('examples/SConscript')

if target_os == 'linux':
	# Build C Samples
	SConscript('csdk/stack/samples/linux/SimpleClientServer/SConscript')

	# Build secure samples
	SConscript('csdk/stack/samples/linux/secure/SConscript')

	# Build C/C++ unit tests
	SConscript('unit_tests.scons')

elif target_os == 'arduino':
	SConscript('csdk/stack/samples/arduino/SimpleClientServer/ocserver/SConscript')
