/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iotivity_ca_CaIpInterface */

#ifndef _Included_org_iotivity_ca_CaIpInterface
#define _Included_org_iotivity_ca_CaIpInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iotivity_ca_CaIpInterface
 * Method:    stateEnabled
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_iotivity_ca_CaIpInterface_stateEnabled
  (JNIEnv *, jclass);

/*
 * Class:     org_iotivity_ca_CaIpInterface
 * Method:    stateDisabled
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_iotivity_ca_CaIpInterface_stateDisabled
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
