#%RAML 0.8
title: OICScannerOperation
version: v1.0-20150602
schemas:
  - Operation: !include oic.r.operational.state.json 
traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a"]
/OperationalStateResURI:
  description: |
    This resource describes the operational and job states on a device.
    The states can be read or set, setting indicates a desired state.
    A device may reject an attempt to set a state that would result
    in adverse operational characteristics.
    The machineStates is a comma separated list of the possible operational states.
    The currentMachineState is the current state of operation of the device.
    The jobStates is a comma separated list of the possible job states.
    The currentJobState is the currently active jobState.
    The runningTime is the ISO8601 encoded elapsed time in the current operational state.
    
    The Values for machineStates are:
    
    'idle': Indicates that new jobs can start processing without waiting.
    
    ‘Processing’: busy with some job or activity
    
    ‘Testing’: calibrating, preparing the unit
    
    ‘Stopped’: error condition occurred
    
    ‘Down’: unit is unavailable

    The Values for jobStates are:
    
    ‘Canceled’ : end state – indicates that the job was canceled either by the remote client application (thru the eSCL interface) or by the user interacting with the scanner directly. Check JobStateReasons for more details.
    
    ‘Aborted’: end state – either an internal device error, or a communication error or a security error
    
    ‘Completed’: job is finished successfully
    
    ‘Pending’: the job was initiated, and the scanner is preparing the scan engine
    
    ‘Processing’: the scanner is processing the job and is transmitting the scan data

  displayName: Scanner Operational State
  is: [ interface ] # valid for all methods
  
  get:
    description: |
      Retrieves the current operational and job states.
    responses:
      200:
        body:
          application/json:
            schema: Operation
            example: |
              {
                "rt":                   "oic.r.operational.state",
                "machineStates":        "idle, processing, stopped, testing, sleep, wake",
                "currentMachineState":  "idle",
                "jobStates":            "pending, processing, canceled, aborted, completed",
                "currentJobState":      "completed",
                "runningTime":          "PT15M20S"
              }

  post:
    description: |
      Sets the desired operational or job state.
    body:
      application/json:
        schema: Operation
        example: |
          {
            "currentMachineState": "wake"
          }
    responses:
      200:
        body:
          application/json:
            schema: Operation
            example: |
              {
                "currentMachineState": "idle"
                "currentJobState": "completed"
              }
      402:
        description: |
          This response is generated by the OIC Server when the client sends:
            An update with an value for currentMachineState that is not found in machineStates.
            An update with an value for currentJobState that is not found in jobStates.
          The server responds with the current resource representation.
        body:
          application/json:
            schema: Operation
            example: |
              {
                "machineStates": "idle, processing, stopped",
                "currentMachineState": "active",
                "jobStates": "pending, pending-held, processing, processing-stopped, canceled, aborted, completed",
                "currentJobState": "completed",
                "runningTime": "PT15M20S",
              }