#######################################################
#	Building wifi adapter
#######################################################

Import('env')

print"Reading wifi adapter script"

target_os = env.get('TARGET_OS')
src_dir = './wifi_adapter/'

#Source files to build common for all platforms
if target_os != 'arduino':
	env.AppendUnique(CA_SRC=[src_dir+'cawifiadapter.c'])
else:
	env.AppendUnique(CA_SRC=[src_dir+'cawifiadapter_singlethread.c'])

#Source files to build in Linux platform
if target_os == 'linux':
	env.AppendUnique(CA_SRC=[src_dir+ 'linux/cawificlient.c',
		src_dir+'linux/cawifinwmonitor.c',
		src_dir+'linux/cawifiserver.c',])

#Source files to build in Tizen platform
if target_os == 'tizen':
	env.AppendUnique(CA_SRC=[src_dir+ 'tizen/cawificlient.c',
		src_dir+'tizen/cawifinwmonitor.c',
		src_dir+'tizen/cawifiserver.c',])

#Source files to build in Arduino platform
if target_os == 'arduino':
	env.AppendUnique(CA_SRC=[src_dir+ 'arduino/cawificlient.cpp',
		src_dir+'arduino/cawifinwmonitor.cpp',
		src_dir+'arduino/cawifiserver.cpp',])

#Source files to build in Android platform
if target_os == 'android':
	env.AppendUnique(CA_SRC=[src_dir+'android/cawificlient.c',
			src_dir+'android/cawifiserver.c',
			src_dir+'android/cawifinwmonitor.c',
			])
