##
# sampleapp build script
##

Import('env')

# Add third party libraries
lib_env = env.Clone()
SConscript(env.get('SRC_DIR') + '/service/third_party_libs.scons', 'lib_env')
sample_env = lib_env.Clone()
target_os = env.get('TARGET_OS')

######################################################################
# Build flags
######################################################################

######################################################################
# Source files and Targets
######################################################################
if target_os == 'linux' :
	# Build linux sample app
	SConscript('linux/SSMTesterApp/SConscript')
	SConscript('linux/THSensorApp/SConscript')
	SConscript('linux/THSensorApp1/SConscript')
	SConscript('linux/HeightSensorApp/SConscript')
	SConscript('linux/WeightSensorApp/SConscript')



