Import('env')
import os

env.AppendUnique(CPPPATH = [
            os.path.join(Dir('.').abspath, 'include')
        ])

if env.get('TARGET_OS') == 'tizen':
	env.AppendUnique(LIBPATH = [env.get('BUILD_DIR')])
else:
	env.AppendUnique(LIBPATH = [os.path.join(env.get('BUILD_DIR'), 'resource/csdk/routing/')])

env.AppendUnique(LIBS = ['routingmanager'])

######################################################################
# Build flags
######################################################################

######################################################################
# Source files and Targets
######################################################################
routing_src = [
    'src/routingutility.c',
    'src/routingmanager.c'
    ]

routinglib = env.StaticLibrary('routingmanager', routing_src)
env.InstallTarget(routinglib, 'routingmanager')
