Import('env')
import os

if env.get('ROUTING') == 'GW':
	env.AppendUnique(CPPPATH = [
				os.path.join(Dir('.').abspath, './include'),
				os.path.join(Dir('.').abspath, './../stack/include'),
				os.path.join(Dir('.').abspath, './../stack/include/internal'),
				os.path.join(Dir('.').abspath, './../logger'),
				os.path.join(Dir('.').abspath, './../../oc_logger/include'),
				os.path.join(Dir('.').abspath, './../ocrandom/include'),
				os.path.join(Dir('.').abspath, './../connectivity/api'),
				os.path.join(Dir('.').abspath, './../connectivity/common/inc')
			])
elif env.get('ROUTING') == 'EP':
	env.AppendUnique(CPPPATH = [
				#TODO: Trim down this include list when routing utility includes only required headers
				os.path.join(Dir('.').abspath, './include'),
				os.path.join(Dir('.').abspath, './../stack/include'),
				os.path.join(Dir('.').abspath, './../stack/include/internal'),
				os.path.join(Dir('.').abspath, './../logger'),
				os.path.join(Dir('.').abspath, './../../oc_logger/include'),
				os.path.join(Dir('.').abspath, './../ocrandom/include'),
				os.path.join(Dir('.').abspath, './../connectivity/api'),
				os.path.join(Dir('.').abspath, './../connectivity/common/inc')
			])

if env.get('TARGET_OS') == 'tizen':
	env.AppendUnique(LIBPATH = [env.get('BUILD_DIR')])
else:
	env.AppendUnique(LIBPATH = [os.path.join(env.get('BUILD_DIR'), 'resource/csdk/routing/')])

env.AppendUnique(LIBS = ['routingmanager'])

######################################################################
# Build flags
######################################################################

######################################################################
# Source files and Targets
######################################################################

if env.get('ROUTING') == 'GW':
	routing_src = [
		'./src/routingutility.c',
		'./src/routingmanager.c',
		'./src/routingtablemanager.c',
		'./src/routingmanagerinterface.c',
		'./src/routingmessageparser.c',
    ]
elif env.get('ROUTING') == 'EP':
	routing_src = [
		'./src/routingutility.c',	
    ]

routinglib = env.StaticLibrary('routingmanager', routing_src)
env.InstallTarget(routinglib, 'routingmanager')
