/*
* //******************************************************************
* //
* // Copyright 2015 Samsung Electronics All Rights Reserved.
* //
* //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
* //
* // Licensed under the Apache License, Version 2.0 (the "License");
* // you may not use this file except in compliance with the License.
* // You may obtain a copy of the License at
* //
* //      http://www.apache.org/licenses/LICENSE-2.0
* //
* // Unless required by applicable law or agreed to in writing, software
* // distributed under the License is distributed on an "AS IS" BASIS,
* // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* // See the License for the specific language governing permissions and
* // limitations under the License.
* //
* //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iotivity_base_OcCertificates */

#ifndef _Included_org_iotivity_base_OcCertificates
#define _Included_org_iotivity_base_OcCertificates
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iotivity_base_OcCertificates
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_iotivity_base_OcCertificates_init
  (JNIEnv *, jclass);

/*
 * Class:     org_iotivity_base_OcCertificates
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_iotivity_base_OcCertificates_destroy
  (JNIEnv *, jclass);

/*
 * Class:     org_iotivity_base_OcCertificates
 * Method:    setCaInfo
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_iotivity_base_OcCertificates_setCaInfo
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_iotivity_base_OcCertificates
 * Method:    generateCaKeyPair
 * Signature: (Ljava/util/List;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_iotivity_base_OcCertificates_generateCaKeyPair
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_iotivity_base_OcCertificates
 * Method:    generateKeyPair
 * Signature: (Ljava/util/List;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_iotivity_base_OcCertificates_generateKeyPair
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_iotivity_base_OcCertificates
 * Method:    issueRootCertificate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_iotivity_base_OcCertificates_issueRootCertificate
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     org_iotivity_base_OcCertificates
 * Method:    issueDeviceCertificate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_iotivity_base_OcCertificates_issueDeviceCertificate
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject, jobject);

/*
 * Class:     org_iotivity_base_OcCertificates
 * Method:    issueCRL
 * Signature: (Ljava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_iotivity_base_OcCertificates_issueCrl
  (JNIEnv *, jclass, jstring, jobject, jobject, jobject);

/*
 * Class:     org_iotivity_base_OcCertificates
 * Method:    revocateCertificate
 * Signature: (Ljava/lang/String;JLjava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_iotivity_base_OcCertificates_revocateCertificate
  (JNIEnv *, jclass, jstring, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
