#######################################################
#       Build BLE adapter for Arduino
#######################################################
import os

Import('connectivity_env')

connectivity_env.PrependUnique(CPPPATH=[Dir('.')])

src_files = [File(src) for src in (
    'cableserver.cpp',
    'cablenwmonitor.cpp',
    'cableclient.cpp',
)]

connectivity_env.AppendUnique(CA_SRC=src_files)
